import { learningCycle, integralMethod } from "@taijifu/canon/method";
import belts from "@taijifu/canon/data/belts";

export default function MetodoPage() {
  return <main>
    <section className="canon-hero"><span className="eyebrow">Método Taijifu</span><h1>Aprender é integrar.</h1><p className="lead">O método organiza conhecimento, prática, evidência, transferência, continuidade e desenvolvimento integral. A progressão não é uma coleção de técnicas nem uma corrida por graduação.</p></section>
    <section className="section"><div className="section-heading"><div><span className="eyebrow">Ciclo de aprendizagem</span><h2>Cinco estados de desenvolvimento.</h2></div><p>O Site e o App usam estes estados para representar aprendizagem sem confundi-la com faixa.</p></div><div className="knowledge-grid">{learningCycle.map((x)=><article className="knowledge-card" key={x.id}><span>{String(x.order).padStart(2,"0")}</span><h3>{x.title}</h3><p>{x.text}</p></article>)}</div></section>
    <section className="section"><div className="prose-panel"><span className="eyebrow">Método Integral</span><h2>Atenção, disciplina e reflexão.</h2><p>{integralMethod.principle}</p><p>{integralMethod.bardonScope}</p></div></section>
    <section className="section"><div className="section-heading"><div><span className="eyebrow">Progressão</span><h2>Dez etapas, uma só formação.</h2></div><p>As etapas acompanham a função pedagógica das dez faixas sem criar uma segunda hierarquia.</p></div><div className="knowledge-stack">{integralMethod.stages.map((s)=>{const belt=belts.find((b)=>b.id===s.beltId);return <article className="prose-panel" key={s.beltId}><span className="eyebrow">{String(s.order).padStart(2,"0")} · {belt?.name}</span><h2>{s.function} — {s.focus}</h2><ul>{s.practices.map((p)=><li key={p}>{p}</li>)}</ul></article>})}</div></section>
    <section className="section"><div className="section-heading"><div><span className="eyebrow">Arquitetura</span><h2>Faixa → Caminho → Núcleo.</h2></div><p>A faixa define a função de desenvolvimento. O Caminho organiza uma competência ampla. O Núcleo é a unidade curricular que recebe conteúdo didático e prática.</p></div><div className="architecture-card wide"><div>10 FAIXAS · FUNÇÃO</div><span>↓</span><div>32 CAMINHOS · ORGANIZAÇÃO</div><span>↓</span><div>128 NÚCLEOS · UNIDADE CURRICULAR</div><span>↓</span><div>APP · ESTUDO + PRÁTICA + EVIDÊNCIA</div></div></section>
    <section className="section"><div className="prose-panel"><span className="eyebrow">Governança</span><h2>Progresso não é graduação.</h2><ul>{integralMethod.rules.map((r)=><li key={r}>{r}</li>)}</ul></div></section>
  </main>;
}
