import { db } from "./index";

export type CommunityVisibility="public"|"members"|"private";
export type CommunityGroupType="general"|"study"|"dojo"|"research"|"mentoring";
export type CommunityPostType="reflection"|"question"|"practice"|"research"|"announcement";
export type CommunityReaction="support"|"insightful"|"practice"|"question";
export type MentoringStatus="open"|"accepted"|"declined"|"completed"|"cancelled";

export async function upsertCommunityProfile(input:{userId:string;handle:string;bio?:string;visibility?:CommunityVisibility}){const [row]=await db()`INSERT INTO community_profiles(user_id,handle,bio,visibility) VALUES(${input.userId},${input.handle},${input.bio??''},${input.visibility??'members'}) ON CONFLICT(user_id) DO UPDATE SET handle=EXCLUDED.handle,bio=EXCLUDED.bio,visibility=EXCLUDED.visibility,updated_at=now() RETURNING user_id,handle,bio,visibility,updated_at::text`;return row;}
export async function getCommunityProfile(userId:string){const [row]=await db()`SELECT p.user_id,p.handle,p.bio,p.visibility,u.display_name,u.current_belt_id FROM community_profiles p JOIN user_profiles u ON u.id=p.user_id WHERE p.user_id=${userId} LIMIT 1`;return row??null;}
export async function getCommunityProfileByHandle(handle:string,viewerUserId:string){const [row]=await db()`SELECT p.user_id,p.handle,p.bio,p.visibility,u.display_name,u.current_belt_id,COUNT(DISTINCT gm.group_id)::int group_count,COUNT(DISTINCT cp.id)::int post_count FROM community_profiles p JOIN user_profiles u ON u.id=p.user_id LEFT JOIN community_group_members gm ON gm.user_id=p.user_id AND gm.status='active' LEFT JOIN community_posts cp ON cp.author_user_id=p.user_id AND cp.status='published' WHERE p.handle=${handle} AND (p.visibility='public' OR p.user_id=${viewerUserId} OR (p.visibility='members' AND EXISTS(SELECT 1 FROM community_group_members mine JOIN community_group_members theirs ON theirs.group_id=mine.group_id WHERE mine.user_id=${viewerUserId} AND theirs.user_id=p.user_id AND mine.status='active' AND theirs.status='active'))) GROUP BY p.user_id,u.display_name,u.current_belt_id LIMIT 1`;return row??null;}

export async function createCommunityGroup(input:{id:string;slug:string;name:string;groupType:CommunityGroupType;ownerUserId:string;description?:string}){const sql=db();return sql.begin(async tx=>{const [group]=await tx`INSERT INTO community_groups(id,slug,name,group_type,owner_user_id,description) VALUES(${input.id},${input.slug},${input.name},${input.groupType},${input.ownerUserId},${input.description??''}) RETURNING id,slug,name,group_type,description,status`;await tx`INSERT INTO community_group_members(group_id,user_id,role,status) VALUES(${input.id},${input.ownerUserId},'owner','active')`;return group;});}
export async function joinCommunityGroup(groupId:string,userId:string){await db()`INSERT INTO community_group_members(group_id,user_id,role,status) VALUES(${groupId},${userId},'member','active') ON CONFLICT(group_id,user_id) DO UPDATE SET status='active'`;}
export async function leaveCommunityGroup(groupId:string,userId:string){await db()`UPDATE community_group_members SET status='left' WHERE group_id=${groupId} AND user_id=${userId} AND role<>'owner'`;}
export async function listCommunityGroups(userId:string){return db()`SELECT g.id,g.slug,g.name,g.group_type,g.description,g.status,COALESCE(m.role,'none') member_role,COALESCE(m.status,'none') member_status,(SELECT COUNT(*)::int FROM community_group_members x WHERE x.group_id=g.id AND x.status='active') member_count FROM community_groups g LEFT JOIN community_group_members m ON m.group_id=g.id AND m.user_id=${userId} WHERE g.status='active' ORDER BY g.created_at DESC`;}
export async function getCommunityGroupBySlug(slug:string,userId:string){const [row]=await db()`SELECT g.id,g.slug,g.name,g.group_type,g.description,g.status,g.owner_user_id,COALESCE(m.role,'none') member_role,COALESCE(m.status,'none') member_status,(SELECT COUNT(*)::int FROM community_group_members x WHERE x.group_id=g.id AND x.status='active') member_count FROM community_groups g LEFT JOIN community_group_members m ON m.group_id=g.id AND m.user_id=${userId} WHERE g.slug=${slug} AND g.status='active' LIMIT 1`;return row??null;}

export async function createCommunityPost(input:{id:string;authorUserId:string;groupId?:string|null;body:string;canonicalEntityIds?:string[];postType?:CommunityPostType}){const sql=db();const [row]=await sql`INSERT INTO community_posts(id,author_user_id,group_id,body,canonical_entity_ids,post_type) VALUES(${input.id},${input.authorUserId},${input.groupId??null},${input.body},${sql.json((input.canonicalEntityIds??[]) as any)},${input.postType??'reflection'}) RETURNING id,author_user_id,group_id,body,canonical_entity_ids,post_type,status,created_at::text`;return row;}
export async function listCommunityFeed(userId:string,limit=50,groupId?:string|null){return db()`SELECT p.id,p.author_user_id,u.display_name,cp.handle,p.group_id,g.name group_name,p.body,p.canonical_entity_ids,p.post_type,p.created_at::text,(SELECT COUNT(*)::int FROM community_comments c WHERE c.post_id=p.id AND c.status='published') comment_count,(SELECT COUNT(*)::int FROM community_reactions r WHERE r.post_id=p.id) reaction_count FROM community_posts p JOIN user_profiles u ON u.id=p.author_user_id LEFT JOIN community_profiles cp ON cp.user_id=p.author_user_id LEFT JOIN community_groups g ON g.id=p.group_id LEFT JOIN community_group_members gm ON gm.group_id=p.group_id AND gm.user_id=${userId} AND gm.status='active' WHERE p.status='published' AND (${groupId??null}::text IS NULL OR p.group_id=${groupId??null}) AND (p.group_id IS NULL OR gm.user_id IS NOT NULL) ORDER BY p.created_at DESC LIMIT ${limit}`;}
export async function createCommunityComment(input:{id:string;postId:string;authorUserId:string;body:string}){const [row]=await db()`INSERT INTO community_comments(id,post_id,author_user_id,body) VALUES(${input.id},${input.postId},${input.authorUserId},${input.body}) RETURNING id,post_id,author_user_id,body,status,created_at::text`;return row;}
export async function listCommunityComments(postId:string,userId:string){return db()`SELECT c.id,c.post_id,c.author_user_id,u.display_name,cp.handle,c.body,c.created_at::text FROM community_comments c JOIN user_profiles u ON u.id=c.author_user_id LEFT JOIN community_profiles cp ON cp.user_id=c.author_user_id JOIN community_posts p ON p.id=c.post_id LEFT JOIN community_group_members gm ON gm.group_id=p.group_id AND gm.user_id=${userId} AND gm.status='active' WHERE c.post_id=${postId} AND c.status='published' AND p.status='published' AND (p.group_id IS NULL OR gm.user_id IS NOT NULL) ORDER BY c.created_at ASC`;}
export async function toggleCommunityReaction(input:{postId:string;userId:string;reaction:CommunityReaction}){const sql=db();const [existing]=await sql`SELECT 1 FROM community_reactions WHERE post_id=${input.postId} AND user_id=${input.userId} AND reaction=${input.reaction} LIMIT 1`;if(existing){await sql`DELETE FROM community_reactions WHERE post_id=${input.postId} AND user_id=${input.userId} AND reaction=${input.reaction}`;return {active:false};}await sql`INSERT INTO community_reactions(post_id,user_id,reaction) VALUES(${input.postId},${input.userId},${input.reaction})`;return {active:true};}

export async function createMentoringRequest(input:{id:string;requesterUserId:string;mentorUserId?:string|null;groupId?:string|null;topic:string;message?:string}){if(input.mentorUserId&&input.mentorUserId===input.requesterUserId)throw new Error('self-mentoring-request-forbidden');const [row]=await db()`INSERT INTO mentoring_requests(id,requester_user_id,mentor_user_id,group_id,topic,message) VALUES(${input.id},${input.requesterUserId},${input.mentorUserId??null},${input.groupId??null},${input.topic},${input.message??''}) RETURNING id,requester_user_id,mentor_user_id,group_id,topic,message,status,created_at::text`;return row;}
export async function listMentoringRequests(userId:string){return db()`SELECT id,requester_user_id,mentor_user_id,group_id,topic,message,status,created_at::text,updated_at::text FROM mentoring_requests WHERE requester_user_id=${userId} OR mentor_user_id=${userId} ORDER BY created_at DESC`;}
export async function updateMentoringRequestStatus(id:string,actorUserId:string,status:MentoringStatus){const [row]=await db()`UPDATE mentoring_requests SET status=${status},updated_at=now() WHERE id=${id} AND ((mentor_user_id=${actorUserId} AND status IN ('accepted','declined','completed')) OR (requester_user_id=${actorUserId} AND status='cancelled')) RETURNING id,status,updated_at::text`;return row??null;}

export async function moderateCommunityPost(input:{postId:string;actorUserId:string;action:'hide'|'restore'|'remove';reason?:string}){const sql=db();const [allowed]=await sql`SELECT 1 FROM community_posts p LEFT JOIN community_group_members gm ON gm.group_id=p.group_id AND gm.user_id=${input.actorUserId} AND gm.status='active' WHERE p.id=${input.postId} AND (p.author_user_id=${input.actorUserId} OR gm.role IN ('moderator','owner')) LIMIT 1`;if(!allowed)throw new Error('community-moderation-forbidden');const next=input.action==='restore'?'published':input.action==='hide'?'hidden':'removed';await sql`UPDATE community_posts SET status=${next},updated_at=now() WHERE id=${input.postId}`;await sql`INSERT INTO community_moderation_events(id,actor_user_id,target_type,target_id,action,reason) VALUES(${`MOD-${crypto.randomUUID()}`},${input.actorUserId},'post',${input.postId},${input.action},${input.reason??''})`;return {status:next};}
