import { db } from "./index";
export type DojoRole="practitioner"|"instructor"|"evaluator"|"guardian"|"admin";
export async function listDojoMemberships(userId:string){const rows=await db()`SELECT d.id dojo_id,d.name,d.slug,m.membership_role,m.status FROM dojo_memberships m JOIN dojos d ON d.id=m.dojo_id WHERE m.user_id=${userId} AND m.status='active' AND d.status='active' ORDER BY d.name,m.membership_role`;return rows.map(r=>({dojoId:r.dojo_id,name:r.name,slug:r.slug,role:r.membership_role as DojoRole,status:r.status}));}
export async function hasDojoRole(userId:string,dojoId:string,roles:DojoRole[]){const [row]=await db()`SELECT 1 ok FROM dojo_memberships WHERE dojo_id=${dojoId} AND user_id=${userId} AND status='active' AND membership_role = ANY(${roles}) LIMIT 1`;return Boolean(row);}
export async function createDojoClass(input:{id:string;dojoId:string;name:string;beltScope?:string|null;instructorUserId:string}){const [row]=await db()`INSERT INTO dojo_classes(id,dojo_id,name,belt_scope,instructor_user_id) VALUES(${input.id},${input.dojoId},${input.name},${input.beltScope??null},${input.instructorUserId}) RETURNING *`;return row;}
export async function listDojoClasses(dojoId:string){return db()`SELECT c.id,c.name,c.belt_scope,c.instructor_user_id,c.status,COUNT(m.user_id)::int member_count FROM dojo_classes c LEFT JOIN dojo_class_members m ON m.class_id=c.id AND m.status='active' WHERE c.dojo_id=${dojoId} GROUP BY c.id ORDER BY c.created_at DESC`;}
export async function addClassMember(classId:string,userId:string){await db()`INSERT INTO dojo_class_members(class_id,user_id,status) VALUES(${classId},${userId},'active') ON CONFLICT(class_id,user_id) DO UPDATE SET status='active'`;}
export async function listClassMembers(classId:string){return db()`SELECT u.id,u.display_name,u.current_belt_id,m.status FROM dojo_class_members m JOIN user_profiles u ON u.id=m.user_id WHERE m.class_id=${classId} AND m.status='active' ORDER BY u.display_name NULLS LAST,u.id`;}
export async function createDojoSession(input:{id:string;dojoId:string;classId?:string|null;instructorUserId:string;sessionType:string;title:string;canonicalEntityIds:string[];safetyProfile:Record<string,unknown>;notes?:string|null;startsAt:string;endsAt?:string|null}){const sql=db();const [row]=await sql`INSERT INTO dojo_sessions(id,dojo_id,class_id,instructor_user_id,session_type,title,canonical_entity_ids,safety_profile,notes,starts_at,ends_at) VALUES(${input.id},${input.dojoId},${input.classId??null},${input.instructorUserId},${input.sessionType},${input.title},${sql.json(input.canonicalEntityIds)},${sql.json(input.safetyProfile)},${input.notes??null},${input.startsAt},${input.endsAt??null}) RETURNING *`;return row;}
export async function listDojoSessions(dojoId:string,limit=50){return db()`SELECT s.id,s.title,s.session_type,s.status,s.starts_at::text,s.ends_at::text,s.canonical_entity_ids,s.safety_profile,s.class_id,u.display_name instructor_name FROM dojo_sessions s JOIN user_profiles u ON u.id=s.instructor_user_id WHERE s.dojo_id=${dojoId} ORDER BY s.starts_at DESC LIMIT ${limit}`;}
export async function setAttendance(sessionId:string,userId:string,status:"expected"|"present"|"absent"|"excused"){await db()`INSERT INTO dojo_attendance(session_id,user_id,status,checked_in_at) VALUES(${sessionId},${userId},${status},${status==='present'?new Date().toISOString():null}) ON CONFLICT(session_id,user_id) DO UPDATE SET status=EXCLUDED.status,checked_in_at=EXCLUDED.checked_in_at`;}
export async function recordSafetyIncident(input:{id:string;dojoId:string;sessionId?:string|null;reporterUserId:string;subjectUserId?:string|null;incidentType:string;severity:string;summary:string;actionsTaken:string;occurredAt:string}){const [row]=await db()`INSERT INTO safety_incidents(id,dojo_id,session_id,reporter_user_id,subject_user_id,incident_type,severity,summary,actions_taken,occurred_at) VALUES(${input.id},${input.dojoId},${input.sessionId??null},${input.reporterUserId},${input.subjectUserId??null},${input.incidentType},${input.severity},${input.summary},${input.actionsTaken},${input.occurredAt}) RETURNING *`;return row;}
export async function listSafetyIncidents(dojoId:string,limit=50){return db()`SELECT id,session_id,incident_type,severity,summary,actions_taken,status,occurred_at::text,created_at::text FROM safety_incidents WHERE dojo_id=${dojoId} ORDER BY occurred_at DESC LIMIT ${limit}`;}
export async function listSubmittedTraversalsForDojo(dojoId:string){return db()`SELECT t.id,t.user_id,u.display_name,t.belt_id,t.status,t.submitted_at::text FROM traversal_attempts t JOIN user_profiles u ON u.id=t.user_id JOIN dojo_memberships m ON m.user_id=t.user_id AND m.dojo_id=${dojoId} AND m.status='active' WHERE t.status IN ('submitted','under-review') ORDER BY t.submitted_at ASC`;}
export async function getDojoDashboard(dojoId:string){const sql=db();const [members,classes,sessions,openIncidents,pendingTraversals]=await Promise.all([sql`SELECT COUNT(DISTINCT user_id)::int count FROM dojo_memberships WHERE dojo_id=${dojoId} AND status='active'`,sql`SELECT COUNT(*)::int count FROM dojo_classes WHERE dojo_id=${dojoId} AND status='active'`,sql`SELECT COUNT(*)::int count FROM dojo_sessions WHERE dojo_id=${dojoId} AND starts_at >= date_trunc('month',now())`,sql`SELECT COUNT(*)::int count FROM safety_incidents WHERE dojo_id=${dojoId} AND status IN ('open','under-review')`,sql`SELECT COUNT(*)::int count FROM traversal_attempts t JOIN dojo_memberships m ON m.user_id=t.user_id AND m.dojo_id=${dojoId} AND m.status='active' WHERE t.status IN ('submitted','under-review')`]);return{members:members[0]?.count??0,classes:classes[0]?.count??0,sessionsThisMonth:sessions[0]?.count??0,openIncidents:openIncidents[0]?.count??0,pendingTraversals:pendingTraversals[0]?.count??0};}
export async function listDojoPractitioners(dojoId:string){return db()`SELECT DISTINCT u.id,u.display_name,u.current_belt_id,m.status FROM dojo_memberships m JOIN user_profiles u ON u.id=m.user_id WHERE m.dojo_id=${dojoId} AND m.status='active' AND m.membership_role='practitioner' ORDER BY u.display_name NULLS LAST,u.id`;}
export async function listDojoStaffGrants(dojoId:string){return db()`SELECT DISTINCT u.id,u.display_name,m.membership_role,c.credential_type,c.scope credential_scope,c.status credential_status,c.valid_until::text,a.authorization_type,a.scope authorization_scope,a.status authorization_status FROM dojo_memberships m JOIN user_profiles u ON u.id=m.user_id LEFT JOIN credentials c ON c.user_id=u.id LEFT JOIN authorizations a ON a.user_id=u.id WHERE m.dojo_id=${dojoId} AND m.status='active' AND m.membership_role IN ('instructor','evaluator','guardian','admin') ORDER BY u.display_name NULLS LAST,u.id`;}
export async function listSessionAttendance(sessionId:string){return db()`WITH target AS (SELECT id,class_id FROM dojo_sessions WHERE id=${sessionId}), roster AS (SELECT m.user_id FROM dojo_class_members m JOIN target t ON t.class_id=m.class_id WHERE m.status='active' UNION SELECT a.user_id FROM dojo_attendance a WHERE a.session_id=${sessionId}) SELECT r.user_id id,u.display_name,u.current_belt_id,COALESCE(a.status,'expected') status,a.checked_in_at::text FROM roster r JOIN user_profiles u ON u.id=r.user_id LEFT JOIN dojo_attendance a ON a.session_id=${sessionId} AND a.user_id=r.user_id ORDER BY u.display_name NULLS LAST,u.id`;}
export async function getDojoClass(classId:string,dojoId:string){const [row]=await db()`SELECT id,dojo_id,name,belt_scope,instructor_user_id,status FROM dojo_classes WHERE id=${classId} AND dojo_id=${dojoId} LIMIT 1`;return row??null;}
export async function getDojoSession(sessionId:string,dojoId:string){const [row]=await db()`SELECT id,dojo_id,class_id,instructor_user_id,session_type,title,status,starts_at::text,ends_at::text,canonical_entity_ids,safety_profile FROM dojo_sessions WHERE id=${sessionId} AND dojo_id=${dojoId} LIMIT 1`;return row??null;}
