import postgres from "postgres";
import type { EvidenceRecordRow, EvaluatorGrantRow, TraversalAttemptRow, UserProfileRow } from "./types";
export * from "./types";
let singleton: ReturnType<typeof postgres> | undefined;
export function isDatabaseConfigured(): boolean { return Boolean(process.env.DATABASE_URL); }
export function db() { if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is required for official persistence"); singleton ??= postgres(process.env.DATABASE_URL,{max:4,prepare:false}); return singleton; }
export async function ensureUserProfile(externalAuthId:string,displayName?:string):Promise<UserProfileRow>{const sql=db();const id=`USR-${externalAuthId}`;const [row]=await sql`INSERT INTO user_profiles (id, external_auth_id, display_name) VALUES (${id},${externalAuthId},${displayName??null}) ON CONFLICT (external_auth_id) DO UPDATE SET display_name=COALESCE(EXCLUDED.display_name,user_profiles.display_name),updated_at=now() RETURNING id,external_auth_id,display_name,current_belt_id`;return{id:row.id,externalAuthId:row.external_auth_id,displayName:row.display_name,currentBeltId:row.current_belt_id};}
export async function insertEvidence(input:Omit<EvidenceRecordRow,"createdAt">):Promise<EvidenceRecordRow>{const sql=db();const [row]=await sql`INSERT INTO evidence_records (id,user_id,kind,status,canonical_entity_id,path_id,belt_id,body,metadata) VALUES (${input.id},${input.userId},${input.kind},${input.status},${input.canonicalEntityId},${input.pathId??null},${input.beltId},${input.body},${sql.json(input.metadata as any)}) RETURNING *,created_at::text`;return{id:row.id,userId:row.user_id,kind:row.kind,status:row.status,canonicalEntityId:row.canonical_entity_id,pathId:row.path_id,beltId:row.belt_id,body:row.body,metadata:row.metadata,createdAt:row.created_at};}
export async function listEvidence(userId:string):Promise<EvidenceRecordRow[]>{const rows=await db()`SELECT *,created_at::text FROM evidence_records WHERE user_id=${userId} ORDER BY created_at DESC`;return rows.map(row=>({id:row.id,userId:row.user_id,kind:row.kind,status:row.status,canonicalEntityId:row.canonical_entity_id,pathId:row.path_id,beltId:row.belt_id,body:row.body,metadata:row.metadata,createdAt:row.created_at}));}
export async function submitTraversal(input:Omit<TraversalAttemptRow,"submittedAt"|"status">):Promise<TraversalAttemptRow>{const sql=db();const [row]=await sql`INSERT INTO traversal_attempts (id,user_id,belt_id,status,reflection,evidence_snapshot) VALUES (${input.id},${input.userId},${input.beltId},'submitted',${input.reflection},${sql.json(input.evidenceSnapshot as any)}) RETURNING *,submitted_at::text`;return{id:row.id,userId:row.user_id,beltId:row.belt_id,status:row.status,reflection:row.reflection,evidenceSnapshot:row.evidence_snapshot,submittedAt:row.submitted_at};}
export async function getTraversal(id:string):Promise<TraversalAttemptRow|null>{const [row]=await db()`SELECT *,submitted_at::text FROM traversal_attempts WHERE id=${id} LIMIT 1`;if(!row)return null;return{id:row.id,userId:row.user_id,beltId:row.belt_id,status:row.status,reflection:row.reflection,evidenceSnapshot:row.evidence_snapshot,submittedAt:row.submitted_at};}
export async function getEvaluatorGrant(userId:string,beltScope:string):Promise<EvaluatorGrantRow|null>{const [row]=await db()`SELECT c.id credential_id,c.credential_type,c.scope credential_scope,a.id authorization_id,a.authorization_type,a.scope authorization_scope FROM credentials c JOIN authorizations a ON a.user_id=c.user_id WHERE c.user_id=${userId} AND c.status='active' AND a.status='active' AND (c.valid_until IS NULL OR c.valid_until>now()) AND c.credential_type='evaluator' AND a.authorization_type='grade-belt' AND (c.scope=${beltScope} OR c.scope='*') AND (a.scope=${beltScope} OR a.scope='*') ORDER BY c.valid_from DESC LIMIT 1`;if(!row)return null;return{credentialId:row.credential_id,credentialType:row.credential_type,credentialScope:row.credential_scope,authorizationId:row.authorization_id,authorizationType:row.authorization_type,authorizationScope:row.authorization_scope};}
export async function getUserProfile(userId:string):Promise<UserProfileRow|null>{const [row]=await db()`SELECT id,external_auth_id,display_name,current_belt_id FROM user_profiles WHERE id=${userId} LIMIT 1`;if(!row)return null;return{id:row.id,externalAuthId:row.external_auth_id,displayName:row.display_name,currentBeltId:row.current_belt_id};}
export async function recordEvaluationAndPromotion(input:{decisionId:string;traversalAttemptId:string;evaluatorUserId:string;evaluatorCredentialId:string;evaluatorAuthorizationId:string;decision:"approve"|"reject"|"needs-more-evidence";rationale:string;userId:string;fromBeltId:string;targetBeltId:string;}):Promise<{promoted:boolean}>{const sql=db();return sql.begin(async tx=>{const [profile]=await tx`SELECT current_belt_id FROM user_profiles WHERE id=${input.userId} FOR UPDATE`;if(!profile)throw new Error("Practitioner profile not found");if(profile.current_belt_id!==input.fromBeltId)throw new Error("Practitioner belt changed after traversal submission");const [existing]=await tx`SELECT id FROM evaluation_decisions WHERE traversal_attempt_id=${input.traversalAttemptId}`;if(existing)throw new Error("Traversal already has an evaluation decision");await tx`INSERT INTO evaluation_decisions (id,traversal_attempt_id,evaluator_user_id,decision,rationale,evaluator_credential_id,evaluator_authorization_id,target_belt_id) VALUES (${input.decisionId},${input.traversalAttemptId},${input.evaluatorUserId},${input.decision},${input.rationale},${input.evaluatorCredentialId},${input.evaluatorAuthorizationId},${input.targetBeltId})`;await tx`UPDATE traversal_attempts SET status=${input.decision==="approve"?"approved":input.decision==="reject"?"rejected":"under-review"},reviewed_at=now() WHERE id=${input.traversalAttemptId}`;if(input.decision!=="approve")return{promoted:false};const promotionId=`PRM-${crypto.randomUUID()}`;await tx`INSERT INTO belt_promotions (id,user_id,from_belt_id,to_belt_id,evaluation_decision_id) VALUES (${promotionId},${input.userId},${input.fromBeltId},${input.targetBeltId},${input.decisionId})`;const updated=await tx`UPDATE user_profiles SET current_belt_id=${input.targetBeltId},updated_at=now() WHERE id=${input.userId} AND current_belt_id=${input.fromBeltId} RETURNING id`;if(updated.length!==1)throw new Error("Promotion update was not applied exactly once");return{promoted:true};});}
