export const pfiSystem = {
  id: "TAIJIFU-PFI-1.0",
  name: "PFI — Preparação Física Integrada",
  principle: "O PFI desenvolve capacidades físicas transferíveis à prática do Taijifu sem criar uma segunda graduação. Faixa, competência técnica e Capacity State permanecem dimensões distintas.",
  objectives: [
    "Desenvolver capacidades físicas úteis para a prática marcial e para a vida cotidiana.",
    "Apoiar controle corporal, robustez, continuidade e recuperação.",
    "Adaptar o treinamento ao estado atual e ao contexto do praticante.",
    "Sustentar longevidade de prática e autonomia.",
  ],
  capacities: [
    { id: "STRENGTH", title: "Força", text: "Capacidade de produzir e controlar força em padrões fundamentais com transferência para a prática." },
    { id: "POWER", title: "Potência", text: "Expressão rápida de força integrada a controle, coordenação e timing." },
    { id: "AEROBIC", title: "Resistência aeróbica", text: "Base de sustentação do esforço e continuidade de prática." },
    { id: "ANAEROBIC", title: "Resistência anaeróbica", text: "Capacidade de lidar com esforços intensos e repetidos dentro de progressão apropriada." },
    { id: "HYPERTROPHY", title: "Musculação", text: "Uso de resistência externa para desenvolvimento de força, estrutura e capacidade funcional." },
    { id: "CALISTHENICS", title: "Calistenia", text: "Controle do próprio corpo, força relativa, estabilidade, coordenação e autonomia." },
    { id: "FUNCTIONAL", title: "Condicionamento integrado", text: "Combinação de padrões locomotores, força, resistência e coordenação em tarefas com propósito funcional." },
    { id: "MOBILITY", title: "Mobilidade", text: "Amplitude de movimento utilizável com controle e integração técnica." },
    { id: "COORDINATION", title: "Coordenação", text: "Organização eficiente de segmentos, ritmo, equilíbrio, dissociação e integração sensório-motora." },
    { id: "SPEED", title: "Velocidade e agilidade", text: "Aceleração, desaceleração, mudança de direção e resposta motora com controle." },
    { id: "ROBUSTNESS", title: "Robustez", text: "Capacidade de sustentar progressivamente as demandas da prática com qualidade e continuidade." },
    { id: "RECOVERY", title: "Recuperação", text: "Gestão da continuidade, intervalo e retorno ao treinamento como parte do processo de adaptação." },
  ],
  capacityStates: [
    { id: "CS-1", title: "Base", text: "Capacidade em construção, com prioridade para consistência, controle e domínio inicial." },
    { id: "CS-2", title: "Estável", text: "Capacidade demonstrada com consistência suficiente para continuar progredindo." },
    { id: "CS-3", title: "Desenvolvimento", text: "Capacidade em expansão por progressão planejada e observável." },
    { id: "CS-4", title: "Sustentação", text: "Capacidade integrada e mantida sob variações de contexto e demanda." },
  ],
  periodization: [
    "Construção — estabelecer base, técnica e consistência.",
    "Desenvolvimento — ampliar capacidades prioritárias.",
    "Integração — aproximar capacidades das demandas da prática marcial.",
    "Consolidação — estabilizar ganhos e reforçar qualidade.",
    "Recuperação — modular a demanda para preservar continuidade e adaptação.",
  ],
  adaptation: [
    "A faixa do praticante não determina automaticamente seu Capacity State.",
    "Capacidades diferentes podem evoluir em ritmos diferentes no mesmo praticante.",
    "Idade, experiência, disponibilidade, contexto e histórico de prática podem modificar o planejamento sem alterar o currículo marcial.",
    "Kids & Youth, adultos, praticantes mais velhos e pessoas retornando de pausas usam o mesmo sistema com adaptação de contexto.",
  ],
  governance: [
    "Capacity State não concede faixa, grau ou promoção.",
    "PFI não cria ranking atlético obrigatório para graduação marcial.",
    "Não existe meta física universal obrigatória para todas as pessoas.",
    "Benchmarks podem apoiar planejamento e acompanhamento, mas não funcionam como Promotion Gate automático.",
    "O App registra progresso físico sem transformar esse progresso em graduação oficial.",
  ],
} as const;
