"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";

type Dojo={dojoId:string;name:string;slug:string;role:string};
type Dashboard={members:number;classes:number;sessionsThisMonth:number;openIncidents:number;pendingTraversals:number};
type ClassRow={id:string;name:string;belt_scope?:string|null;member_count:number};
type SessionRow={id:string;title:string;session_type:string;status:string;starts_at:string;class_id?:string|null};
type Student={id:string;display_name?:string|null;current_belt_id:string};
type Traversal={id:string;user_id:string;display_name?:string|null;belt_id:string;status:string;submitted_at:string};
type Incident={id:string;incident_type:string;severity:string;summary:string;status:string;occurred_at:string};

type Tab="overview"|"classes"|"sessions"|"attendance"|"traversals"|"safety"|"assistant";
const tabs:readonly [Tab,string][]=[["overview","Visão geral"],["classes","Turmas"],["sessions","Sessões"],["attendance","Presença"],["traversals","Travessias"],["safety","Safety"],["assistant","IA Taijifu"]];
const sessionTypes=["curriculum-class","technical-lab","representative-practice","sparring-lab","pfi-strength","pfi-endurance","pfi-integrated-conditioning","kinetic-arts","integral-practice","open-lab","assessment","research-lab"];

async function api<T>(url:string,init?:RequestInit):Promise<T>{const r=await fetch(url,{...init,headers:{"content-type":"application/json",...(init?.headers??{})},cache:"no-store"});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error??`HTTP ${r.status}`);return data as T;}

export function DojoWorkspace(){
 const [dojos,setDojos]=useState<Dojo[]>([]);const [dojoId,setDojoId]=useState("");const [tab,setTab]=useState<Tab>("overview");const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 const [dashboard,setDashboard]=useState<Dashboard|null>(null);const [classes,setClasses]=useState<ClassRow[]>([]);const [sessions,setSessions]=useState<SessionRow[]>([]);const [students,setStudents]=useState<Student[]>([]);const [traversals,setTraversals]=useState<Traversal[]>([]);const [incidents,setIncidents]=useState<Incident[]>([]);
 const [aiQuery,setAiQuery]=useState("Como posso planejar uma sessão segura para N001?");const [aiSurface,setAiSurface]=useState<"instructor-assistant"|"research-assistant">("instructor-assistant");const [aiResult,setAiResult]=useState<{answer:string;mode:string;sources:Array<{ref:string;tier:string;canonicalEntityId:string;title:string}>}|null>(null);
 const [selectedClass,setSelectedClass]=useState("");const [selectedSession,setSelectedSession]=useState("");const [roster,setRoster]=useState<Student[]>([]);const [attendance,setAttendance]=useState<Array<Student&{status:string}>>([]);
 const activeDojo=useMemo(()=>dojos.find(d=>d.dojoId===dojoId),[dojos,dojoId]);
 const qs=(path:string)=>`${path}?dojoId=${encodeURIComponent(dojoId)}`;
 async function bootstrap(){setLoading(true);setError("");try{const data=await api<{dojos:Dojo[]}>("/api/dojos");setDojos(data.dojos);setDojoId(v=>v||data.dojos[0]?.dojoId||"");}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar dojo");}finally{setLoading(false)}}
 async function refresh(){if(!dojoId)return;setLoading(true);setError("");try{const [d,c,s,st,i]=await Promise.all([api<{dashboard:Dashboard}>(qs("/api/dashboard")),api<{classes:ClassRow[]}>(qs("/api/classes")),api<{sessions:SessionRow[]}>(qs("/api/sessions")),api<{practitioners:Student[]}>(qs("/api/students")),api<{incidents:Incident[]}>(qs("/api/safety"))]);setDashboard(d.dashboard);setClasses(c.classes);setSessions(s.sessions);setStudents(st.practitioners);setIncidents(i.incidents);try{const t=await api<{traversals:Traversal[]}>(qs("/api/traversals"));setTraversals(t.traversals)}catch{setTraversals([])}}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar workspace");}finally{setLoading(false)}}
 useEffect(()=>{void bootstrap()},[]);useEffect(()=>{if(dojoId)void refresh()},[dojoId]);
 async function createClass(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await api("/api/classes",{method:"POST",body:JSON.stringify({dojoId,name:f.get("name"),beltScope:f.get("beltScope")||undefined})});e.currentTarget.reset();await refresh()}
 async function createSession(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await api("/api/sessions",{method:"POST",body:JSON.stringify({dojoId,title:f.get("title"),sessionType:f.get("sessionType"),classId:f.get("classId")||undefined,startsAt:new Date(String(f.get("startsAt"))).toISOString(),canonicalEntityIds:String(f.get("canonicalEntityIds")||"").split(",").map(x=>x.trim()).filter(Boolean),safetyProfile:{contactLevel:f.get("contactLevel"),intensityLevel:f.get("intensityLevel")}})});e.currentTarget.reset();await refresh()}
 async function loadRoster(classId:string){setSelectedClass(classId);if(!classId){setRoster([]);return}const d=await api<{members:Student[]}>(`/api/roster?dojoId=${encodeURIComponent(dojoId)}&classId=${encodeURIComponent(classId)}`);setRoster(d.members)}
 async function loadAttendance(sessionId:string){setSelectedSession(sessionId);if(!sessionId){setAttendance([]);return}const d=await api<{attendance:Array<Student&{status:string}>}>(`/api/attendance/list?dojoId=${encodeURIComponent(dojoId)}&sessionId=${encodeURIComponent(sessionId)}`);setAttendance(d.attendance)}
 async function markAttendance(userId:string,status:"present"|"absent"|"excused"){await api("/api/attendance",{method:"POST",body:JSON.stringify({dojoId,sessionId:selectedSession,userId,status})});await loadAttendance(selectedSession)}
 async function createIncident(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await api("/api/safety",{method:"POST",body:JSON.stringify({dojoId,incidentType:f.get("incidentType"),severity:f.get("severity"),summary:f.get("summary"),actionsTaken:f.get("actionsTaken"),sessionId:f.get("sessionId")||undefined,occurredAt:new Date().toISOString()})});e.currentTarget.reset();await refresh()}
 async function askAssistant(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=await api<{answer:string;mode:string;sources:Array<{ref:string;tier:string;canonicalEntityId:string;title:string}>}>("/api/ai/query",{method:"POST",body:JSON.stringify({dojoId,query:aiQuery,surface:aiSurface})});setAiResult(d)}
 async function decideTraversal(id:string,decision:"approve"|"reject"|"needs-more-evidence"){const rationale=window.prompt("Registre a justificativa da decisão (mín. 12 caracteres):");if(!rationale)return;await api("/api/traversals/decision",{method:"POST",body:JSON.stringify({dojoId,traversalAttemptId:id,decision,rationale})});await refresh()}
 if(loading&&!dojos.length)return <main className="shell"><p>Carregando workspace...</p></main>;
 if(error&&!dojos.length)return <main className="shell"><section className="card"><span className="pill danger">Acesso indisponível</span><h1>Dojo Workspace</h1><p className="muted">{error}</p><p className="muted">O modo oficial exige autenticação e DATABASE_URL configurados.</p></section></main>;
 return <main className="shell">
   <header className="brand"><strong>TAIJIFU <span className="gold">DOJO</span></strong><div className="toolbar"><select value={dojoId} onChange={e=>setDojoId(e.target.value)}>{dojos.map(d=><option value={d.dojoId} key={d.dojoId}>{d.name} · {d.role}</option>)}</select><span className="muted">Tehkné Solutions</span></div></header>
   <section className="hero"><span className="pill">P6 · MVP operacional</span><h1>{activeDojo?.name??"Dojo Workspace"}</h1><p className="muted">Turmas, sessões, presença, Safety e Travessias consumindo o mesmo Canon e o mesmo Promotion Gate.</p></section>
   <nav className="tabs">{tabs.map(([id,label])=><button key={id} className={tab===id?"tab active":"tab"} onClick={()=>setTab(id)}>{label}</button>)}</nav>
   {error&&<div className="alert">{error}</div>}
   {tab==="overview"&&<><section className="grid">{[["Alunos ativos",dashboard?.members??0],["Turmas",dashboard?.classes??0],["Sessões no mês",dashboard?.sessionsThisMonth??0],["Travessias pendentes",dashboard?.pendingTraversals??0],["Safety aberto",dashboard?.openIncidents??0]].map(([l,v])=><article className="card" key={String(l)}><div className="metric">{v}</div><div className="muted">{l}</div></article>)}</section><section className="columns"><div className="card"><h2>Operação de hoje</h2><div className="list">{sessions.slice(0,5).map(s=><div className="row" key={s.id}><div><strong>{s.title}</strong><div className="muted">{s.session_type} · {new Date(s.starts_at).toLocaleString("pt-BR")}</div></div><span className="pill">{s.status}</span></div>)||null}{!sessions.length&&<p className="muted">Nenhuma sessão registrada.</p>}</div></div><aside className="card"><span className="pill danger">Safety Hard Stop</span><h2>Safety acima da agenda.</h2><p className="muted">Tap, Stop Response, safeguarding e condição de parada prevalecem sobre treino, avaliação ou graduação.</p></aside></section></>}
   {tab==="classes"&&<section className="columns"><div className="card"><h2>Turmas</h2><div className="list">{classes.map(c=><button className="row rowbtn" key={c.id} onClick={()=>void loadRoster(c.id)}><div><strong>{c.name}</strong><div className="muted">{c.belt_scope||"Faixas mistas"} · {c.member_count} praticantes</div></div><span>→</span></button>)}</div>{selectedClass&&<div className="subpanel"><h3>Roster</h3>{roster.map(s=><div className="row" key={s.id}><span>{s.display_name||s.id}</span><span className="pill">{s.current_belt_id}</span></div>)}</div>}</div><form className="card form" onSubmit={createClass}><h2>Nova turma</h2><label>Nome<input name="name" minLength={3} required/></label><label>Faixa / escopo<input name="beltScope" placeholder="BELT-WHITE"/></label><button className="btn" type="submit">Criar turma</button></form></section>}
   {tab==="sessions"&&<section className="columns"><div className="card"><h2>Sessões</h2><div className="list">{sessions.map(s=><div className="row" key={s.id}><div><strong>{s.title}</strong><div className="muted">{s.session_type} · {new Date(s.starts_at).toLocaleString("pt-BR")}</div></div><span className="pill">{s.status}</span></div>)}</div></div><form className="card form" onSubmit={createSession}><h2>Nova sessão</h2><label>Título<input name="title" required minLength={3}/></label><label>Tipo<select name="sessionType">{sessionTypes.map(x=><option value={x} key={x}>{x}</option>)}</select></label><label>Turma<select name="classId"><option value="">Sem turma</option>{classes.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Início<input name="startsAt" type="datetime-local" required/></label><label>Entidades canônicas<input name="canonicalEntityIds" placeholder="NUC-N001, PATH-C01"/></label><div className="twocol"><label>Contato<select name="contactLevel"><option>C0</option><option>C1</option><option>C2</option><option>C3</option><option>C4</option><option>C5</option></select></label><label>Intensidade<select name="intensityLevel"><option>I0</option><option>I1</option><option>I2</option><option>I3</option><option>I4</option></select></label></div><button className="btn" type="submit">Criar sessão</button></form></section>}
   {tab==="attendance"&&<section className="card"><h2>Check-in de presença</h2><label>Selecione a sessão<select value={selectedSession} onChange={e=>void loadAttendance(e.target.value)}><option value="">Escolha...</option>{sessions.map(s=><option value={s.id} key={s.id}>{s.title} · {new Date(s.starts_at).toLocaleDateString("pt-BR")}</option>)}</select></label>{selectedSession&&<div className="list spaced">{attendance.length?attendance.map(a=><div className="row" key={a.id}><div><strong>{a.display_name||a.id}</strong><div className="muted">{a.current_belt_id}</div></div><div className="actions"><button className="mini" onClick={()=>void markAttendance(a.id,"present")}>Presente</button><button className="mini" onClick={()=>void markAttendance(a.id,"excused")}>Justificado</button><button className="mini dangerbtn" onClick={()=>void markAttendance(a.id,"absent")}>Ausente</button><span className="pill">{a.status}</span></div></div>):<p className="muted">Ainda não há registros de presença nesta sessão. O roster da turma pode ser pré-carregado numa evolução do scheduler.</p>}</div>}</section>}
   {tab==="traversals"&&<section className="card"><h2>Fila de Travessias</h2><p className="muted">Aprovar aqui chama o mesmo Promotion Gate server-side; não existe promoção paralela do Dojo.</p><div className="list spaced">{traversals.map(t=><div className="row" key={t.id}><div><strong>{t.display_name||t.user_id}</strong><div className="muted">{t.belt_id} · enviada {new Date(t.submitted_at).toLocaleString("pt-BR")}</div></div><div className="actions"><button className="mini" onClick={()=>void decideTraversal(t.id,"approve")}>Aprovar</button><button className="mini" onClick={()=>void decideTraversal(t.id,"needs-more-evidence")}>Mais evidências</button><button className="mini dangerbtn" onClick={()=>void decideTraversal(t.id,"reject")}>Rejeitar</button></div></div>)}{!traversals.length&&<p className="muted">Nenhuma Travessia disponível para este usuário/Dojo ou o usuário atual não possui role de avaliador.</p>}</div></section>}
   {tab==="assistant"&&<section className="columns"><form className="card form" onSubmit={askAssistant}><span className="pill">Canon RAG</span><h2>IA Taijifu</h2><label>Modo<select value={aiSurface} onChange={e=>setAiSurface(e.target.value as "instructor-assistant"|"research-assistant")}><option value="instructor-assistant">Assistant de instrutor</option>{(activeDojo?.role==="guardian"||activeDojo?.role==="admin")&&<option value="research-assistant">Assistant de pesquisa</option>}</select></label><label>Pergunta<textarea value={aiQuery} onChange={e=>setAiQuery(e.target.value)} minLength={3} maxLength={1600} required/></label><button className="btn" type="submit">Consultar Canon</button><p className="muted">Prioridade: Current Canon → Approved → Research → Historical. A IA não altera Canon, faixa ou credencial.</p></form><article className="card"><h2>Resposta fundamentada</h2>{aiResult?<><p style={{whiteSpace:"pre-wrap"}}>{aiResult.answer}</p><div className="list">{aiResult.sources.map(s=><div className="row" key={s.ref}><div><strong>[{s.ref}] {s.title}</strong><div className="muted">{s.tier} · {s.canonicalEntityId}</div></div></div>)}</div><span className="pill">{aiResult.mode}</span></>:<p className="muted">Faça uma pergunta para consultar as entidades do Canon.</p>}</article></section>}
   {tab==="safety"&&<section className="columns"><div className="card"><h2>Safety Log</h2><div className="list">{incidents.map(i=><div className="row" key={i.id}><div><strong>{i.incident_type} · {i.severity}</strong><div>{i.summary}</div><div className="muted">{new Date(i.occurred_at).toLocaleString("pt-BR")}</div></div><span className="pill danger">{i.status}</span></div>)}{!incidents.length&&<p className="muted">Nenhum incidente registrado.</p>}</div></div><form className="card form" onSubmit={createIncident}><span className="pill danger">Safety</span><h2>Novo registro</h2><label>Tipo<select name="incidentType"><option value="incident">Incident</option><option value="near-miss">Near Miss</option><option value="hard-stop">Hard Stop</option><option value="safeguarding">Safeguarding</option></select></label><label>Severidade<select name="severity"><option value="low">Baixa</option><option value="moderate">Moderada</option><option value="high">Alta</option><option value="critical">Crítica</option></select></label><label>Sessão<select name="sessionId"><option value="">Sem sessão</option>{sessions.map(s=><option value={s.id} key={s.id}>{s.title}</option>)}</select></label><label>Resumo<textarea name="summary" required minLength={8}/></label><label>Ações tomadas<textarea name="actionsTaken" required minLength={3}/></label><button className="btn dangerfill" type="submit">Registrar Safety</button></form></section>}
 </main>
}
