"use client";

import { useEffect, useMemo, useState } from "react";
import type { LearningStep } from "@taijifu/evidence/types";
import { createBeltRuntime, type BeltRuntimeConfig } from "./belt-runtime";
import { ProgressRing } from "./progress";

type QuizQuestion={id:string;prompt:string;options:string[];correctIndex:number};
const runtimeKey=(config:BeltRuntimeConfig)=>`${config.slug}:${config.beltId}:${config.nextBeltId}:${config.nucleusStart}:${config.nucleusCount}:${config.pathIds.join(",")}`;

export function useBeltRuntime(config:BeltRuntimeConfig){
  const key=runtimeKey(config);
  const runtime=useMemo(()=>createBeltRuntime(config),[key]);
  const[state,setState]=useState(()=>runtime.emptyState());
  useEffect(()=>{const sync=()=>setState(runtime.read());sync();return runtime.subscribe(sync);},[runtime]);
  const complete=(nucleusId:string,step:LearningStep)=>setState(runtime.completeStep(nucleusId,step));
  const reset=()=>{runtime.reset();setState(runtime.read());};
  const stats=useMemo(()=>{const totalSteps=runtime.nucleusIds.length*3;let completedSteps=0,completedNuclei=0;for(const id of runtime.nucleusIds){const row=state.progress[id]??{};const count=Number(Boolean(row.lesson))+Number(Boolean(row.practice))+Number(Boolean(row.quiz));completedSteps+=count;if(count===3)completedNuclei+=1;}return{completedSteps,totalSteps,completedNuclei,xp:completedSteps*10,percent:Math.round((completedSteps/totalSteps)*100),evidenceCount:state.evidence.length,pathCheckpoints:Object.values(state.pathCheckpoints).filter(Boolean).length,traversalStatus:state.traversal.status};},[runtime,state]);
  return{runtime,state,complete,reset,stats};
}

export function BeltProgressSummary({config}:{config:BeltRuntimeConfig}){const{runtime,stats,reset}=useBeltRuntime(config);return <div className="progress-panel"><ProgressRing value={stats.percent} label={`Faixa ${config.label}`}/><div className="progress-copy"><span className="eyebrow">Progresso local · schema v2</span><h3>{stats.completedNuclei} de {runtime.nucleusIds.length} Núcleos consolidados</h3><p>{stats.completedSteps} de {stats.totalSteps} etapas · {stats.xp} XP · {stats.evidenceCount} evidências · {stats.pathCheckpoints}/{config.pathIds.length} checkpoints de Caminho.</p><p><strong>Travessia:</strong> {stats.traversalStatus}. Conclusão do App não concede promoção automática.</p></div>{stats.completedSteps>0?<button className="text-button" onClick={reset}>Reiniciar demo</button>:null}</div>;}

export function BeltNucleusProgress({config,nucleusId}:{config:BeltRuntimeConfig;nucleusId:string}){const{state}=useBeltRuntime(config);const row=state.progress[nucleusId]??{};const count=Number(Boolean(row.lesson))+Number(Boolean(row.quiz))+Number(Boolean(row.practice));return <div className="mini-progress" aria-label={`${count} de 3 etapas concluídas`}>{(["lesson","practice","quiz"] as LearningStep[]).map(step=><span key={step} className={row[step]?"done":""} title={{lesson:"Lição",practice:"Prática",quiz:"Checkpoint"}[step]}/>)}</div>;}

export function BeltLessonActions({config,nucleusId,quizQuestions,practiceText}:{config:BeltRuntimeConfig;nucleusId:string;quizQuestions:QuizQuestion[];practiceText:string}){const{state,complete}=useBeltRuntime(config);const row=state.progress[nucleusId]??{};const[answers,setAnswers]=useState<Record<string,number>>({});const[submitted,setSubmitted]=useState(false);const score=quizQuestions.reduce((sum,q)=>sum+(answers[q.id]===q.correctIndex?1:0),0);const quizPassed=submitted&&score===quizQuestions.length;const submitQuiz=()=>{setSubmitted(true);const nextScore=quizQuestions.reduce((sum,q)=>sum+(answers[q.id]===q.correctIndex?1:0),0);if(nextScore===quizQuestions.length)complete(nucleusId,"quiz");};return <div className="learning-stack"><section className={`learning-card ${row.lesson?"is-complete":""}`}><div className="step-index">01</div><div><span className="eyebrow">Lição</span><h2>{config.functionName}</h2><p>Explique o objetivo funcional do Núcleo com suas próprias palavras antes de avançar.</p><button className="btn primary" onClick={()=>complete(nucleusId,"lesson")}>{row.lesson?"Lição concluída":"Concluir lição"}</button></div></section><section className={`learning-card ${row.practice?"is-complete":""} ${!row.lesson?"is-locked":""}`}><div className="step-index">02</div><div><span className="eyebrow">Prática guiada</span><h2>Testar em contexto</h2><p>{practiceText}</p><div className="safety-box"><strong>Safety Gate</strong><span>Execute apenas dentro do nível de contato, intensidade e supervisão adequados. Pare diante de qualquer condição insegura.</span></div><button className="btn primary" disabled={!row.lesson} onClick={()=>complete(nucleusId,"practice")}>{row.practice?"Prática registrada":row.lesson?"Registrar prática":"Conclua a lição primeiro"}</button></div></section><section className={`learning-card ${row.quiz?"is-complete":""} ${!row.practice?"is-locked":""}`}><div className="step-index">03</div><div className="quiz-block"><span className="eyebrow">Checkpoint</span><h2>Verificar compreensão</h2>{quizQuestions.map((q,qi)=><fieldset key={q.id} className="question" disabled={!row.practice}><legend>{qi+1}. {q.prompt}</legend>{q.options.map((option,oi)=><label key={option} className="option"><input type="radio" name={q.id} checked={answers[q.id]===oi} onChange={()=>setAnswers(prev=>({...prev,[q.id]:oi}))}/><span>{option}</span></label>)}</fieldset>)}<div className="checkpoint-actions"><button className="btn primary" disabled={!row.practice} onClick={submitQuiz}>{row.practice?"Validar checkpoint":"Registre a prática primeiro"}</button>{submitted?<span className={quizPassed?"feedback success":"feedback warning"}>{quizPassed?`Aprovado · ${score}/${quizQuestions.length}`:`Revise e tente novamente · ${score}/${quizQuestions.length}`}</span>:null}</div></div></section></div>;}

export function BeltNucleusReflection({config,nucleusId,pathId}:{config:BeltRuntimeConfig;nucleusId:string;pathId:string}){const{runtime,state}=useBeltRuntime(config);const[text,setText]=useState("");const[saved,setSaved]=useState(false);const complete=state.progress[nucleusId]?.lesson&&state.progress[nucleusId]?.practice&&state.progress[nucleusId]?.quiz;const previous=state.evidence.find(record=>record.canonicalEntityId===nucleusId&&record.kind==="reflection");const save=()=>{if(!text.trim())return;runtime.addEvidence({kind:"reflection",canonicalEntityId:nucleusId,pathId,body:text});setSaved(true);setText("");};return <section className={`learning-card evidence-card ${!complete?"is-locked":""}`}><div className="step-index">04</div><div><span className="eyebrow">Evidência reflexiva</span><h2>Registrar aprendizagem</h2><p>Descreva o que mudou na sua leitura ou execução, onde houve falha e o que será testado na próxima prática.</p>{previous?<div className="evidence-existing"><strong>Último registro</strong><p>{previous.body}</p></div>:null}<textarea className="reflection-input" disabled={!complete} value={text} onChange={event=>setText(event.target.value)} placeholder={complete?"Minha principal aprendizagem foi...":"Conclua lição, prática e checkpoint para registrar evidência."}/><div className="checkpoint-actions"><button className="btn primary" disabled={!complete||!text.trim()} onClick={save}>Registrar reflexão</button>{saved?<span className="feedback success">Evidência registrada no histórico local.</span>:null}</div></div></section>;}

export function BeltPathCheckpoints({config,paths}:{config:BeltRuntimeConfig;paths:{id:string;code:string;name:string}[]}){const{runtime,state}=useBeltRuntime(config);const[drafts,setDrafts]=useState<Record<string,string>>({});const[message,setMessage]=useState<Record<string,string>>({});return <div className="journey checkpoint-journey">{paths.map(path=>{const ids=runtime.pathNucleusIds(path.id);const completeCount=ids.filter(id=>{const row=state.progress[id]??{};return row.lesson&&row.practice&&row.quiz;}).length;const unlocked=completeCount===ids.length;const completed=Boolean(state.pathCheckpoints[path.id]);const submit=()=>{const result=runtime.completePathCheckpoint(path.id,drafts[path.id]??"");setMessage(current=>({...current,[path.id]:result.ok?"Checkpoint registrado.":"Complete os quatro Núcleos e escreva sua reflexão."}));};return <section className={`journey-path checkpoint-path ${completed?"checkpoint-complete":""}`} key={path.id}><div className="journey-head"><div className="journey-index">{path.code}</div><div><span className="meta">Checkpoint de Caminho</span><h3>{path.name}</h3><p>{completeCount}/4 Núcleos completos. O checkpoint registra síntese; não concede graduação.</p></div></div><textarea className="reflection-input" disabled={!unlocked||completed} value={drafts[path.id]??""} onChange={event=>setDrafts(current=>({...current,[path.id]:event.target.value}))} placeholder={completed?"Checkpoint concluído.":unlocked?"Que princípio conecta os quatro Núcleos?":"Conclua os quatro Núcleos para liberar."}/><div className="checkpoint-actions"><button className="btn primary" disabled={!unlocked||completed||!(drafts[path.id]??"").trim()} onClick={submit}>{completed?"Checkpoint concluído":"Registrar checkpoint"}</button>{message[path.id]?<span className={completed?"feedback success":"feedback warning"}>{message[path.id]}</span>:null}</div></section>;})}</div>;}

export function BeltTraversalPanel({config}:{config:BeltRuntimeConfig}){const{runtime,state}=useBeltRuntime(config);const[text,setText]=useState("");const[message,setMessage]=useState("");const ready=state.traversal.status==="ready"||state.traversal.status==="submitted";const submitted=state.traversal.status==="submitted";const submit=()=>{const result=runtime.submitTraversal(text);setMessage(result.ok?"Travessia enviada para avaliação futura. Nenhuma promoção foi concedida.":"Complete os checkpoints e escreva a reflexão final.");};return <section className={`traversal-panel ${ready?"is-ready":""}`}><div><span className="eyebrow">Travessia {config.label} · simulação</span><h2>{submitted?"Enviada para revisão.":ready?"Pronta para submissão.":"Ainda bloqueada."}</h2><p>A Travessia reúne evidências da função <strong>{config.functionName}</strong>. O App registra a submissão; a promoção continua sendo decisão formal de avaliador autorizado.</p></div><div className="promotion-gate"><strong>PROMOTION GATE</strong><span>{config.beltId} → {config.nextBeltId}: <b>NOT AUTOMATIC</b></span><span>Requer evaluator decision + authorization + persistent evidence.</span></div><textarea className="reflection-input inverse-input" disabled={!ready||submitted} value={text} onChange={event=>setText(event.target.value)} placeholder={submitted?state.traversal.reflection:ready?`O que a Faixa ${config.label} transformou na sua prática?`:"Conclua os Caminhos para liberar."}/><div className="checkpoint-actions"><button className="btn light" disabled={!ready||submitted||!text.trim()} onClick={submit}>{submitted?"Travessia enviada":"Enviar para futura avaliação"}</button>{message?<span className="traversal-message">{message}</span>:null}</div></section>;}

export function BeltEvidenceHistory({config}:{config:BeltRuntimeConfig}){const{state}=useBeltRuntime(config);return <div className="history-list">{state.events.length===0?<div className="empty-state"><strong>Nenhum evento ainda.</strong><p>Conclua uma etapa ou registre evidência para começar o histórico da faixa.</p></div>:state.events.map(entry=><article className="history-row" key={entry.id}><div><span className="meta">{entry.type}</span><strong>{entry.detail}</strong></div><time dateTime={entry.createdAt}>{new Date(entry.createdAt).toLocaleString("pt-BR")}</time></article>)}</div>;}
