import type { BeltLocalState, EvidenceKind, EvidenceRecord, LearningEvent, LearningStep } from "@taijifu/evidence/types";

export type BeltRuntimeConfig={
  slug:string; beltId:string; nextBeltId:string; label:string; functionName:string;
  nucleusStart:number; nucleusCount:number; pathIds:readonly string[];
};

export function createBeltRuntime(config:BeltRuntimeConfig){
  const storageKey=`taijifu:${config.slug}-belt-state:v2`;
  const changeEvent=`taijifu-${config.slug}-state`;
  const nucleusIds=Array.from({length:config.nucleusCount},(_,i)=>`NUC-N${String(i+config.nucleusStart).padStart(3,"0")}`);
  const emptyState=():BeltLocalState=>({schemaVersion:2,progress:{},evidence:[],pathCheckpoints:{},traversal:{status:"locked"},events:[]});
  const makeEvent=(type:LearningEvent["type"],detail:string,canonicalEntityId?:string):LearningEvent=>({id:crypto.randomUUID(),createdAt:new Date().toISOString(),type,canonicalEntityId,detail});
  const read=():BeltLocalState=>{if(typeof window==="undefined")return emptyState();const raw=window.localStorage.getItem(storageKey);if(!raw)return emptyState();try{const parsed=JSON.parse(raw) as BeltLocalState;return parsed.schemaVersion===2?parsed:emptyState();}catch{return emptyState();}};
  const writeLocal=(state:BeltLocalState)=>{window.localStorage.setItem(storageKey,JSON.stringify(state));window.dispatchEvent(new CustomEvent(changeEvent));};
  const syncSnapshot=async(state:BeltLocalState)=>{try{await fetch("/api/practice/state",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({beltId:config.beltId,state})});}catch{/* local cache remains available offline */}};
  const write=(state:BeltLocalState)=>{writeLocal(state);void syncSnapshot(state);};
  const hydrate=async():Promise<BeltLocalState>=>{if(typeof window==="undefined")return emptyState();try{const response=await fetch(`/api/practice/state?beltId=${encodeURIComponent(config.beltId)}`,{cache:"no-store"});if(response.ok){const payload=await response.json() as {state?:BeltLocalState|null};if(payload.state?.schemaVersion===2){writeLocal(payload.state);return payload.state;}}}catch{/* unauthenticated/offline mode keeps local cache */}return read();};
  const subscribe=(callback:()=>void)=>{window.addEventListener("storage",callback);window.addEventListener(changeEvent,callback as EventListener);return()=>{window.removeEventListener("storage",callback);window.removeEventListener(changeEvent,callback as EventListener);};};
  const mirrorEvidence=async(input:{kind:EvidenceKind;canonicalEntityId:string;body:string;pathId?:string;metadata?:EvidenceRecord["metadata"]})=>{try{await fetch("/api/evidence",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(input)});}catch{/* snapshot still records local/offline work */}};
  const completeStep=(nucleusId:string,step:LearningStep)=>{const state=read();const current=state.progress[nucleusId]??{};if(current[step])return state;state.progress[nucleusId]={...current,[step]:true};state.events.unshift(makeEvent("step-completed",`${nucleusId}: ${step}`,nucleusId));write(state);return state;};
  const addEvidence=(input:{kind:EvidenceKind;canonicalEntityId:string;body:string;pathId?:string;metadata?:EvidenceRecord["metadata"];status?:EvidenceRecord["status"]})=>{const state=read();const record:EvidenceRecord={id:crypto.randomUUID(),createdAt:new Date().toISOString(),kind:input.kind,status:input.status??"recorded",canonicalEntityId:input.canonicalEntityId,pathId:input.pathId,beltId:config.beltId,body:input.body.trim(),metadata:input.metadata};state.evidence.unshift(record);state.events.unshift(makeEvent("evidence-recorded",`${input.kind}: ${input.canonicalEntityId}`,input.canonicalEntityId));write(state);void mirrorEvidence(input);return record;};
  const isNucleusComplete=(state:BeltLocalState,nucleusId:string)=>{const row=state.progress[nucleusId]??{};return Boolean(row.lesson&&row.practice&&row.quiz);};
  const pathNucleusIds=(pathId:string)=>{const index=config.pathIds.indexOf(pathId);if(index<0)return[];return nucleusIds.slice(index*4,index*4+4);};
  const completePathCheckpoint=(pathId:string,reflection:string)=>{const state=read();const ids=pathNucleusIds(pathId);if(!ids.every(id=>isNucleusComplete(state,id)))return{ok:false as const,reason:"learning-incomplete"};if(!reflection.trim())return{ok:false as const,reason:"reflection-required"};state.pathCheckpoints[pathId]=true;state.evidence.unshift({id:crypto.randomUUID(),createdAt:new Date().toISOString(),kind:"path-checkpoint",status:"recorded",canonicalEntityId:pathId,pathId,beltId:config.beltId,body:reflection.trim()});state.events.unshift(makeEvent("path-checkpoint-completed",`${pathId}: checkpoint registrado`,pathId));if(config.pathIds.every(id=>state.pathCheckpoints[id])&&nucleusIds.every(id=>isNucleusComplete(state,id)))state.traversal.status="ready";write(state);void mirrorEvidence({kind:"path-checkpoint",canonicalEntityId:pathId,pathId,body:reflection.trim()});return{ok:true as const};};
  const mirrorTraversal=async(reflection:string)=>{try{const response=await fetch("/api/traversal/submit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({beltId:config.beltId,reflection})});if(response.ok)return;/* 401/503 intentionally mean local demo/offline mode */if(response.status===401||response.status===503)return;const state=read();if(state.traversal.status==="submitted"){state.traversal={status:"ready"};state.events.unshift(makeEvent("traversal-submitted",`Submissão oficial não persistida (${response.status}); Travessia retornou para pronta.`,config.beltId));writeLocal(state);}}catch{/* offline: retain local submission */}};
  const submitTraversal=(reflection:string)=>{const state=read();const ready=config.pathIds.every(id=>state.pathCheckpoints[id])&&nucleusIds.every(id=>isNucleusComplete(state,id));if(!ready)return{ok:false as const,reason:"requirements-incomplete"};if(reflection.trim().length<20)return{ok:false as const,reason:"reflection-too-short"};const submittedAt=new Date().toISOString();state.traversal={status:"submitted",submittedAt,reflection:reflection.trim()};state.evidence.unshift({id:crypto.randomUUID(),createdAt:submittedAt,kind:"traversal-submission",status:"submitted",canonicalEntityId:config.beltId,beltId:config.beltId,body:reflection.trim(),metadata:{promotionGranted:false,nextBelt:config.nextBeltId,decisionRequired:true}});state.events.unshift(makeEvent("traversal-submitted",`Travessia ${config.label} enviada. Nenhuma promoção concedida.`,config.beltId));write(state);void mirrorTraversal(reflection.trim());return{ok:true as const};};
  const reset=()=>{const state=emptyState();state.events.push(makeEvent("demo-reset",`Cache local da Faixa ${config.label} reiniciado.`));write(state);};
  return{config,storageKey,nucleusIds,emptyState,read,write,hydrate,subscribe,completeStep,addEvidence,isNucleusComplete,pathNucleusIds,completePathCheckpoint,submitTraversal,reset};
}
