"use client";
import { useEffect,useMemo,useState } from "react";

type SynthesisState={schemaVersion:1;reflections:Record<string,string>;checks:Record<string,boolean>;submittedAt?:string};
const KEY="taijifu:black:synthesis:v1";
const axes=[
  {id:"VIEW-SYN-SYSTEM",title:"Síntese do sistema",prompt:"Como as 4 Bases, 12 Princípios, 32 Caminhos e 128 Núcleos formam um único sistema coerente?"},
  {id:"VIEW-SYN-EVIDENCE",title:"Portfólio de evidências",prompt:"Que evidências representam melhor sua evolução, transferência e retenção ao longo das faixas?"},
  {id:"VIEW-SYN-JUDGMENT",title:"Julgamento e responsabilidade",prompt:"Como você diferencia competência pessoal, autoridade, credencial, autorização e responsabilidade institucional?"},
  {id:"VIEW-SYN-CONTINUITY",title:"Continuidade e legado",prompt:"Que compromissos concretos preservam Safety, aprendizagem contínua, transmissão responsável e evolução do Canon?"}
] as const;
const empty=():SynthesisState=>({schemaVersion:1,reflections:{},checks:{}});
function read():SynthesisState{if(typeof window==="undefined")return empty();try{return {...empty(),...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return empty()}}
function write(state:SynthesisState){localStorage.setItem(KEY,JSON.stringify(state));window.dispatchEvent(new Event("taijifu:black-synthesis"));}
export function BlackSynthesisPanel(){const[state,setState]=useState<SynthesisState>(empty);useEffect(()=>{const sync=()=>setState(read());sync();window.addEventListener("taijifu:black-synthesis",sync);return()=>window.removeEventListener("taijifu:black-synthesis",sync)},[]);const completed=useMemo(()=>axes.filter(a=>state.checks[a.id]&&state.reflections[a.id]?.trim()).length,[state]);const update=(id:string,text:string)=>{const next={...state,reflections:{...state.reflections,[id]:text}};write(next);setState(next)};const check=(id:string)=>{const next={...state,checks:{...state.checks,[id]:!state.checks[id]}};write(next);setState(next)};const submit=()=>{if(completed!==axes.length)return;const next={...state,submittedAt:new Date().toISOString()};write(next);setState(next)};return <div className="learning-stack">{axes.map((axis,index)=><section className={`learning-card ${state.checks[axis.id]?"is-complete":""}`} key={axis.id}><div className="step-index">{String(index+1).padStart(2,"0")}</div><div><span className="eyebrow">View de síntese · não cria Canon</span><h2>{axis.title}</h2><p>{axis.prompt}</p><textarea className="reflection-input" value={state.reflections[axis.id]??""} onChange={e=>update(axis.id,e.target.value)} placeholder="Registre sua síntese com exemplos e evidências..."/><label className="option"><input type="checkbox" checked={Boolean(state.checks[axis.id])} onChange={()=>check(axis.id)}/><span>Revisei esta dimensão e consigo justificá-la com evidências.</span></label></div></section>)}<section className="traversal-panel"><div><span className="eyebrow">Síntese Preta · App</span><h2>{state.submittedAt?"Síntese registrada.":`${completed}/4 dimensões consolidadas`}</h2><p>Este registro não cria C33, N129, credencial, autorização ou promoção. Ele organiza evidências sobre o Canon já existente.</p></div><div className="promotion-gate"><strong>CANON GATE</strong><span>Caminhos oficiais: <b>C01–C32</b></span><span>Núcleos oficiais: <b>N001–N128</b></span><span>Novos Caminhos/Núcleos na Preta: <b>0</b></span></div><button className="btn light" disabled={completed!==axes.length||Boolean(state.submittedAt)} onClick={submit}>{state.submittedAt?"Síntese registrada":"Registrar síntese final"}</button></section></div>}
