"use client";
import type { EvidenceKind, EvidenceRecord, LearningStep, WhiteBeltLocalState } from "@taijifu/evidence/types";
import { createBeltRuntime } from "./belt-runtime";
import { whiteConfig } from "./white-runtime";

const runtime=createBeltRuntime(whiteConfig);
export const STORAGE_KEY=runtime.storageKey;
export const WHITE_NUCLEUS_IDS=runtime.nucleusIds;
export const WHITE_PATH_IDS=whiteConfig.pathIds;
export const emptyState=runtime.emptyState;
export const hydrateWhiteState=runtime.hydrate;
export const readWhiteState=runtime.read;
export const writeWhiteState=(state:WhiteBeltLocalState)=>runtime.write(state);
export const subscribeWhiteState=runtime.subscribe;
export const completeLearningStep=(nucleusId:string,step:LearningStep)=>runtime.completeStep(nucleusId,step);
export const addEvidence=(input:{kind:EvidenceKind;canonicalEntityId:string;body:string;pathId?:string;metadata?:EvidenceRecord["metadata"];status?:EvidenceRecord["status"]})=>runtime.addEvidence(input);
export const isNucleusComplete=(state:WhiteBeltLocalState,nucleusId:string)=>runtime.isNucleusComplete(state,nucleusId);
export const pathNucleusIds=(pathId:string)=>runtime.pathNucleusIds(pathId);
export const isPathLearningComplete=(state:WhiteBeltLocalState,pathId:string)=>pathNucleusIds(pathId).every(id=>isNucleusComplete(state,id));
export const completePathCheckpoint=(pathId:string,reflection:string)=>runtime.completePathCheckpoint(pathId,reflection);
export const submitWhiteTraversal=(reflection:string)=>runtime.submitTraversal(reflection);
export const resetWhiteDemo=runtime.reset;
