"use client";

import { useState } from "react";
import { addOrangeEvidence, completeOrangePathCheckpoint, orangePathNucleusIds, submitOrangeTraversal } from "./orange-evidence-store";
import { useOrangeProgress } from "./orange-progress";

export function OrangeNucleusReflection({nucleusId,pathId}:{nucleusId:string;pathId:string}){const{state}=useOrangeProgress();const[text,setText]=useState("");const[saved,setSaved]=useState(false);const complete=state.progress[nucleusId]?.lesson&&state.progress[nucleusId]?.practice&&state.progress[nucleusId]?.quiz;const previous=state.evidence.find(record=>record.canonicalEntityId===nucleusId&&record.kind==="reflection");const save=()=>{if(!text.trim())return;addOrangeEvidence({kind:"reflection",canonicalEntityId:nucleusId,pathId,body:text});setSaved(true);setText("");};return <section className={`learning-card evidence-card ${!complete?"is-locked":""}`}><div className="step-index">04</div><div><span className="eyebrow">Evidência reflexiva</span><h2>Explicar o que você compreendeu</h2><p>Registre a relação mecânica ou funcional que ficou mais clara e onde sua compreensão ainda falha.</p>{previous?<div className="evidence-existing"><strong>Último registro</strong><p>{previous.body}</p></div>:null}<textarea className="reflection-input" disabled={!complete} value={text} onChange={event=>setText(event.target.value)} placeholder={complete?"Agora compreendo que...":"Conclua lição, prática e checkpoint para registrar evidência."}/><div className="checkpoint-actions"><button className="btn primary" disabled={!complete||!text.trim()} onClick={save}>Registrar reflexão</button>{saved?<span className="feedback success">Evidência registrada no histórico local.</span>:null}</div></div></section>;}

const PATHS=[{id:"PATH-C07",code:"C07",name:"Mecânica e Estrutura"},{id:"PATH-C08",code:"C08",name:"Função e Ferramenta"},{id:"PATH-C09",code:"C09",name:"Defesa e Contramedida"}];
export function OrangePathCheckpoints(){const{state}=useOrangeProgress();const[drafts,setDrafts]=useState<Record<string,string>>({});const[message,setMessage]=useState<Record<string,string>>({});return <div className="journey checkpoint-journey">{PATHS.map(path=>{const ids=orangePathNucleusIds(path.id);const completeCount=ids.filter(id=>{const row=state.progress[id]??{};return row.lesson&&row.practice&&row.quiz;}).length;const unlocked=completeCount===ids.length;const completed=Boolean(state.pathCheckpoints[path.id]);const submit=()=>{const result=completeOrangePathCheckpoint(path.id,drafts[path.id]??"");setMessage(current=>({...current,[path.id]:result.ok?"Checkpoint registrado.":"Complete os quatro Núcleos e escreva sua reflexão."}));};return <section className={`journey-path checkpoint-path ${completed?"checkpoint-complete":""}`} key={path.id}><div className="journey-head"><div className="journey-index">{path.code}</div><div><span className="meta">Checkpoint de Caminho</span><h3>{path.name}</h3><p>{completeCount}/4 Núcleos completos. O checkpoint registra síntese de compreensão; não concede graduação.</p></div></div><div><textarea className="reflection-input" disabled={!unlocked||completed} value={drafts[path.id]??""} onChange={event=>setDrafts(current=>({...current,[path.id]:event.target.value}))} placeholder={completed?"Checkpoint concluído.":unlocked?"Que princípio une os quatro Núcleos deste Caminho?":"Conclua os quatro Núcleos para liberar."}/><div className="checkpoint-actions"><button className="btn primary" disabled={!unlocked||completed||!(drafts[path.id]??"").trim()} onClick={submit}>{completed?"Checkpoint concluído":"Registrar checkpoint"}</button>{message[path.id]?<span className={completed?"feedback success":"feedback warning"}>{message[path.id]}</span>:null}</div></div></section>;})}</div>;}

export function OrangeTraversalPanel(){const{state}=useOrangeProgress();const[text,setText]=useState("");const[message,setMessage]=useState("");const ready=state.traversal.status==="ready"||state.traversal.status==="submitted";const submitted=state.traversal.status==="submitted";const submit=()=>{const result=submitOrangeTraversal(text);setMessage(result.ok?"Travessia enviada para avaliação futura. Nenhuma promoção foi concedida.":"Complete os três checkpoints e escreva a reflexão final.");};return <section className={`traversal-panel ${ready?"is-ready":""}`}><div><span className="eyebrow">Travessia Laranja · simulação</span><h2>{submitted?"Enviada para revisão.":ready?"Pronta para submissão.":"Ainda bloqueada."}</h2><p>A Travessia reúne evidências da função <strong>Compreender</strong>. O App registra a submissão; promoção para Vermelha continua sendo decisão formal de avaliador autorizado.</p></div><div className="promotion-gate"><strong>PROMOTION GATE</strong><span>BELT-ORANGE → BELT-RED: <b>NOT AUTOMATIC</b></span><span>Requer evaluator decision + authorization + persistent evidence.</span></div><textarea className="reflection-input inverse-input" disabled={!ready||submitted} value={text} onChange={event=>setText(event.target.value)} placeholder={submitted?state.traversal.reflection:ready?"Como sua compreensão de mecânica, função e contramedida mudou?":"Conclua C07, C08 e C09 para liberar."}/><div className="checkpoint-actions"><button className="btn light" disabled={!ready||submitted||!text.trim()} onClick={submit}>{submitted?"Travessia enviada":"Enviar para futura avaliação"}</button>{message?<span className="traversal-message">{message}</span>:null}</div></section>;}

export function OrangeEvidenceHistory(){const{state}=useOrangeProgress();return <div className="history-list">{state.events.length===0?<div className="empty-state"><strong>Nenhum evento ainda.</strong><p>Conclua uma etapa ou registre evidência para começar o histórico da Laranja.</p></div>:state.events.map(entry=><article className="history-row" key={entry.id}><div><span className="meta">{entry.type}</span><strong>{entry.detail}</strong></div><time dateTime={entry.createdAt}>{new Date(entry.createdAt).toLocaleString("pt-BR")}</time></article>)}</div>;}
