"use client";

import { useState } from "react";
import { addYellowEvidence, completeYellowPathCheckpoint, submitYellowTraversal, yellowPathNucleusIds } from "./yellow-evidence-store";
import { useYellowProgress } from "./yellow-progress";

export function YellowNucleusReflection({nucleusId,pathId}:{nucleusId:string;pathId:string}){
  const{state}=useYellowProgress();const[text,setText]=useState("");const[saved,setSaved]=useState(false);const complete=state.progress[nucleusId]?.lesson&&state.progress[nucleusId]?.practice&&state.progress[nucleusId]?.quiz;const previous=state.evidence.find(record=>record.canonicalEntityId===nucleusId&&record.kind==="reflection");
  const save=()=>{if(!text.trim())return;addYellowEvidence({kind:"reflection",canonicalEntityId:nucleusId,pathId,body:text});setSaved(true);setText("");};
  return <section className={`learning-card evidence-card ${!complete?"is-locked":""}`}><div className="step-index">04</div><div><span className="eyebrow">Evidência reflexiva</span><h2>Registrar o que você percebeu</h2><p>Descreva o sinal, relação ou mudança que ficou mais clara durante a prática e o que ainda precisa observar.</p>{previous?<div className="evidence-existing"><strong>Último registro</strong><p>{previous.body}</p></div>:null}<textarea className="reflection-input" disabled={!complete} value={text} onChange={event=>setText(event.target.value)} placeholder={complete?"Eu passei a perceber...":"Conclua lição, prática e checkpoint para registrar evidência."}/><div className="checkpoint-actions"><button className="btn primary" disabled={!complete||!text.trim()} onClick={save}>Registrar reflexão</button>{saved?<span className="feedback success">Evidência registrada no histórico local.</span>:null}</div></div></section>;
}

const PATHS=[{id:"PATH-C04",code:"C04",name:"Distância e Espaço"},{id:"PATH-C05",code:"C05",name:"Leitura e Timing"},{id:"PATH-C06",code:"C06",name:"Estrutura e Intenção"}];

export function YellowPathCheckpoints(){
  const{state}=useYellowProgress();const[drafts,setDrafts]=useState<Record<string,string>>({});const[message,setMessage]=useState<Record<string,string>>({});
  return <div className="journey checkpoint-journey">{PATHS.map(path=>{const ids=yellowPathNucleusIds(path.id);const completeCount=ids.filter(id=>{const row=state.progress[id]??{};return row.lesson&&row.practice&&row.quiz;}).length;const unlocked=completeCount===ids.length;const completed=Boolean(state.pathCheckpoints[path.id]);const submit=()=>{const result=completeYellowPathCheckpoint(path.id,drafts[path.id]??"");setMessage(current=>({...current,[path.id]:result.ok?"Checkpoint registrado.":"Complete os quatro Núcleos e escreva sua reflexão."}));};return <section className={`journey-path checkpoint-path ${completed?"checkpoint-complete":""}`} key={path.id}><div className="journey-head"><div className="journey-index">{path.code}</div><div><span className="meta">Checkpoint de Caminho</span><h3>{path.name}</h3><p>{completeCount}/4 Núcleos completos. O checkpoint registra síntese de percepção; não concede graduação.</p></div></div><div><textarea className="reflection-input" disabled={!unlocked||completed} value={drafts[path.id]??""} onChange={event=>setDrafts(current=>({...current,[path.id]:event.target.value}))} placeholder={completed?"Checkpoint concluído.":unlocked?"O que os quatro Núcleos fizeram você perceber de forma diferente?":"Conclua os quatro Núcleos para liberar."}/><div className="checkpoint-actions"><button className="btn primary" disabled={!unlocked||completed||!(drafts[path.id]??"").trim()} onClick={submit}>{completed?"Checkpoint concluído":"Registrar checkpoint"}</button>{message[path.id]?<span className={completed?"feedback success":"feedback warning"}>{message[path.id]}</span>:null}</div></div></section>;})}</div>;
}

export function YellowTraversalPanel(){
  const{state}=useYellowProgress();const[text,setText]=useState("");const[message,setMessage]=useState("");const ready=state.traversal.status==="ready"||state.traversal.status==="submitted";const submitted=state.traversal.status==="submitted";const submit=()=>{const result=submitYellowTraversal(text);setMessage(result.ok?"Travessia enviada para avaliação futura. Nenhuma promoção foi concedida.":"Complete os três checkpoints e escreva a reflexão final.");};
  return <section className={`traversal-panel ${ready?"is-ready":""}`}><div><span className="eyebrow">Travessia Amarela · simulação</span><h2>{submitted?"Enviada para revisão.":ready?"Pronta para submissão.":"Ainda bloqueada."}</h2><p>A Travessia reúne evidências da função <strong>Perceber</strong>. O App registra a submissão; promoção para Laranja continua sendo decisão formal de avaliador autorizado.</p></div><div className="promotion-gate"><strong>PROMOTION GATE</strong><span>BELT-YELLOW → BELT-ORANGE: <b>NOT AUTOMATIC</b></span><span>Requer evaluator decision + authorization + persistent evidence.</span></div><textarea className="reflection-input inverse-input" disabled={!ready||submitted} value={text} onChange={event=>setText(event.target.value)} placeholder={submitted?state.traversal.reflection:ready?"O que mudou na sua capacidade de perceber distância, timing e estrutura?":"Conclua C04, C05 e C06 para liberar."}/><div className="checkpoint-actions"><button className="btn light" disabled={!ready||submitted||!text.trim()} onClick={submit}>{submitted?"Travessia enviada":"Enviar para futura avaliação"}</button>{message?<span className="traversal-message">{message}</span>:null}</div></section>;
}

export function YellowEvidenceHistory(){const{state}=useYellowProgress();return <div className="history-list">{state.events.length===0?<div className="empty-state"><strong>Nenhum evento ainda.</strong><p>Conclua uma etapa ou registre evidência para começar o histórico da Amarela.</p></div>:state.events.map(entry=><article className="history-row" key={entry.id}><div><span className="meta">{entry.type}</span><strong>{entry.detail}</strong></div><time dateTime={entry.createdAt}>{new Date(entry.createdAt).toLocaleString("pt-BR")}</time></article>)}</div>;}
