import nodes from "@taijifu/content/data/nodes";
import paths from "@taijifu/canon/data/paths";
import nuclei from "@taijifu/canon/data/nuclei";
import { OrangeProgressSummary, OrangeNucleusProgress } from "../../components/orange-progress";

export default function OrangeBelt(){
  const all=nodes as any[];
  const orangePaths=(paths as any[]).filter(p=>p.beltId==="BELT-ORANGE");
  const orangeNuclei=(nuclei as any[]).filter(n=>n.beltId==="BELT-ORANGE").sort((a,b)=>a.order-b.order);
  return <main>
    <section className="belt-hero"><div><span className="eyebrow">Faixa 03 · Laranja</span><h1>Compreender.</h1><p className="lead">Entender mecânica, função, seleção de ferramentas, defesa e contramedidas antes de aumentar complexidade ou pressão.</p></div><div className="belt-mark"><span>03</span><strong>橙</strong><small>12 Núcleos</small></div></section>
    <OrangeProgressSummary />
    <section className="section"><div className="section-heading"><div><span className="eyebrow">Mapa da faixa</span><h2>Três Caminhos de compreensão.</h2></div><p>A Laranja transforma percepção em entendimento funcional. O App registra aprendizagem e evidência; graduação permanece fora da lógica de XP.</p></div><div className="journey">{orangePaths.map((path,index)=>{const pathNuclei=orangeNuclei.filter(n=>n.pathId===path.id);return <section className="journey-path" key={path.id}><div className="journey-head"><div className="journey-index">{String(index+1).padStart(2,"0")}</div><div><span className="meta">{path.code}</span><h3>{path.name}</h3><p>{path.function}</p></div></div><div className="nucleus-list">{pathNuclei.map(n=>{const lesson=all.find(node=>node.canonicalEntityId===n.id&&node.type==="lesson");return <a className="nucleus-row" key={n.id} href={`/belt/laranja/${n.code.toLowerCase()}`}><span className="nucleus-code">{n.code}</span><div><strong>{n.name}</strong><p>{lesson?.summary}</p></div><OrangeNucleusProgress nucleusId={n.id}/><span className="row-arrow">→</span></a>;})}</div></section>;})}</div></section>
    <section className="section next-stage-section"><div className="section-heading"><div><span className="eyebrow">Integração</span><h2>Depois dos 12 Núcleos.</h2></div><p>Feche C07–C09, registre sínteses e prepare a Travessia Laranja para avaliação futura.</p></div><div className="next-stage-grid"><a className="path-card" href="/belt/laranja/checkpoint"><span className="path-number">A</span><div><span className="meta">C07–C09</span><h3>Checkpoints de Caminho</h3><p>Conecte mecânica, função e contramedida em evidência reflexiva.</p><span className="text-link">Abrir checkpoints →</span></div></a><a className="path-card dark-card" href="/belt/laranja/travessia"><span className="path-number">B</span><div><span className="meta">Travessia</span><h3>Submissão para avaliação</h3><p>Consolide a função Compreender sem converter XP em graduação.</p><span className="text-link">Abrir Travessia →</span></div></a><a className="path-card" href="/belt/laranja/history"><span className="path-number">C</span><div><span className="meta">Evidence Timeline</span><h3>Histórico da Laranja</h3><p>Veja etapas, reflexões e checkpoints registrados nesta faixa.</p><span className="text-link">Ver histórico →</span></div></a></div></section>
  </main>;
}
